import type { Collection } from "./types";

export const COLLECTIONS: Collection[] = [
  {
    handle: "thes",
    title: "Tous les thés",
    universe: "thes",
    accent: "gold",
    description:
      "L'intégralité de notre sélection de thés — verts, blancs, noirs et matcha, cueillis chez nos producteurs partenaires.",
  },
  {
    handle: "the-vert",
    title: "Thé vert",
    universe: "thes",
    accent: "green",
    description: "Frais, végétal, tout en subtilité — nos thés verts du Japon, de Chine et au-delà.",
    filterKey: "type",
    filterValue: "vert",
  },
  {
    handle: "the-blanc",
    title: "Thé blanc",
    universe: "thes",
    accent: "white",
    description: "Le thé le moins transformé, délicat et légèrement sucré.",
    filterKey: "type",
    filterValue: "blanc",
  },
  {
    handle: "the-noir",
    title: "Thé noir",
    universe: "thes",
    accent: "black",
    description: "Corsés, ambrés, parfaits en toute saison — nos thés noirs d'Inde, du Sri Lanka et de Chine.",
    filterKey: "type",
    filterValue: "noir",
  },
  {
    handle: "matcha",
    title: "Matcha",
    universe: "thes",
    accent: "matcha",
    description: "Thé vert japonais réduit en poudre fine, pour l'usuel ou la cérémonie.",
    filterKey: "type",
    filterValue: "matcha",
  },
  {
    handle: "best-sellers",
    title: "Best-sellers",
    universe: "thes",
    accent: "gold",
    description: "Les thés préférés de notre maison, plébiscités saison après saison.",
    filterKey: "selection",
    filterValue: "best-sellers",
  },
  {
    handle: "bio",
    title: "Thés biologiques",
    universe: "thes",
    accent: "green",
    description: "Certifiés issus de l'agriculture biologique, du jardin à la tasse.",
    filterKey: "selection",
    filterValue: "bio",
  },
  {
    handle: "grand-cru",
    title: "Grands crus",
    universe: "thes",
    accent: "gold",
    description: "Des récoltes rares et limitées, réservées aux amateurs exigeants.",
    filterKey: "selection",
    filterValue: "grand-cru",
  },
  {
    handle: "origine-japon",
    title: "Thés du Japon",
    universe: "thes",
    accent: "matcha",
    description: "Sencha, gyokuro, hojicha et matcha — l'art du thé japonais.",
    filterKey: "origin",
    filterValue: "japon",
  },
  {
    handle: "origine-chine",
    title: "Thés de Chine",
    universe: "thes",
    accent: "green",
    description: "Berceau du thé, la Chine offre une diversité inégalée de crus.",
    filterKey: "origin",
    filterValue: "chine",
  },
  {
    handle: "origine-inde",
    title: "Thés d'Inde",
    universe: "thes",
    accent: "black",
    description: "Darjeeling, Assam, Nilgiri — la puissance et la finesse des jardins indiens.",
    filterKey: "origin",
    filterValue: "inde",
  },
  {
    handle: "origine-nepal",
    title: "Thés du Népal",
    universe: "thes",
    accent: "gold",
    description: "Des jardins d'altitude aux notes florales et musquées.",
    filterKey: "origin",
    filterValue: "nepal",
  },
  {
    handle: "origine-coree",
    title: "Thés de Corée",
    universe: "thes",
    accent: "green",
    description: "Une tradition confidentielle, entre douceur marine et fraîcheur végétale.",
    filterKey: "origin",
    filterValue: "coree",
  },
  {
    handle: "origine-vietnam",
    title: "Thés du Vietnam",
    universe: "thes",
    accent: "green",
    description: "Des thés artisanaux aux notes fumées et florales.",
    filterKey: "origin",
    filterValue: "vietnam",
  },
  {
    handle: "origine-sri-lanka",
    title: "Thés du Sri Lanka",
    universe: "thes",
    accent: "black",
    description: "Les fameux thés de Ceylan, vifs et lumineux.",
    filterKey: "origin",
    filterValue: "sri-lanka",
  },
  {
    handle: "infusions-rooibos",
    title: "Infusions & Rooibos",
    universe: "infusions-rooibos",
    accent: "rooibos",
    description: "Sans théine, pour tous les moments de la journée — rooibos, tisanes et infusions de plantes.",
  },
  {
    handle: "the-glace",
    title: "Thés glacés",
    universe: "thes-glaces",
    accent: "green",
    description: "Nos assemblages pensés pour l'infusion à froid, rafraîchissants et gourmands.",
  },
  {
    handle: "chai-latte",
    title: "Chai Latté",
    universe: "chai-latte",
    accent: "chai",
    description: "Le thé noir épicé indien, prêt à marier avec le lait de votre choix.",
  },
  {
    handle: "bien-etre-detox",
    title: "Bien-être & Detox",
    universe: "bien-etre-detox",
    accent: "wellness",
    description: "Des mélanges pensés pour accompagner votre rituel bien-être au quotidien.",
  },
  {
    handle: "coffrets-accessoires",
    title: "Coffrets & Accessoires",
    universe: "coffrets-accessoires",
    accent: "gold",
    description: "De quoi offrir et infuser dans les règles de l'art.",
  },
];

export const NEED_LABELS: Record<string, string> = {
  sommeil: "Sommeil",
  digestion: "Digestion",
  relaxation: "Relaxation",
  energie: "Énergie",
  detox: "Detox",
  immunite: "Immunité",
};

export const NOTE_LABELS: Record<string, string> = {
  fruite: "Fruité",
  bergamote: "Bergamote",
  floral: "Floral",
  epice: "Épicé",
  gourmand: "Gourmand",
  "mentholé": "Mentholé",
};

export const ORIGIN_LABELS: Record<string, string> = {
  japon: "Japon",
  chine: "Chine",
  inde: "Inde",
  nepal: "Népal",
  coree: "Corée",
  vietnam: "Vietnam",
  "sri-lanka": "Sri Lanka",
};

export const ACCESSORY_LABELS: Record<string, string> = {
  "carte-cadeau": "Cartes cadeaux",
  infuseur: "Infuseurs",
  tasse: "Tasses",
  boite: "Boîtes",
  coffret: "Coffrets",
};
