import type { Collection } from "./types";

export const COLLECTIONS: Collection[] = [
  {
    handle: "rituels-cheveux",
    title: "Rituels Cheveux",
    category: "infusion",
    line: "cheveux",
    accent: "cuivre",
    description:
      "Des infusions botaniques pensées pour la santé du cheveu — de la racine à la pointe, cultivées avec la même exigence que nos thés.",
  },
  {
    handle: "chute-fortification",
    title: "Chute & Fortification",
    category: "infusion",
    line: "cheveux",
    accent: "cuivre",
    description: "Ortie, prêle et biotine végétale pour fortifier la fibre à la racine.",
    filterKey: "hairNeed",
    filterValue: "chute",
  },
  {
    handle: "densite-volume",
    title: "Densité & Volume",
    category: "infusion",
    line: "cheveux",
    accent: "or",
    description: "Bambou et ginseng pour une chevelure plus dense et plus fournie.",
    filterKey: "hairNeed",
    filterValue: "densite",
  },
  {
    handle: "brillance-texture",
    title: "Brillance & Texture",
    category: "infusion",
    line: "cheveux",
    accent: "rose",
    description: "Prêle et romarin pour une brillance miroir et une texture disciplinée.",
    filterKey: "hairNeed",
    filterValue: "brillance",
  },
  {
    handle: "cuir-chevelu-equilibre",
    title: "Cuir Chevelu & Équilibre",
    category: "infusion",
    line: "cheveux",
    accent: "sauge",
    description: "Bardane et sauge pour apaiser et équilibrer le cuir chevelu.",
    filterKey: "hairNeed",
    filterValue: "cuir-chevelu",
  },
  {
    handle: "anti-stress-beaute",
    title: "Anti-Stress & Beauté",
    category: "infusion",
    line: "cheveux",
    accent: "taupe",
    description: "Ashwagandha et camomille pour une beauté qui commence par l'apaisement.",
    filterKey: "hairNeed",
    filterValue: "anti-stress",
  },
  {
    handle: "eclat-protection",
    title: "Éclat & Protection",
    category: "infusion",
    line: "cheveux",
    accent: "creme",
    description: "Baies de goji et vitamine E pour protéger l'éclat naturel du cheveu.",
    filterKey: "hairNeed",
    filterValue: "eclat",
  },
  {
    handle: "rituels-feminins",
    title: "Rituels Féminins",
    category: "infusion",
    line: "feminin",
    accent: "rose",
    description: "Des infusions botaniques pour accompagner chaque saison du cycle féminin.",
  },
  {
    handle: "cycle-feminin",
    title: "Cycle féminin",
    category: "infusion",
    line: "feminin",
    accent: "rose",
    description: "Framboisier et camomille pour apaiser les journées de cycle.",
    filterKey: "feminineNeed",
    filterValue: "cycle",
  },
  {
    handle: "confort-premenstruel",
    title: "Confort prémenstruel",
    category: "infusion",
    line: "feminin",
    accent: "terracotta",
    description: "Gattilier et mélisse pour retrouver l'équilibre avant le cycle.",
    filterKey: "feminineNeed",
    filterValue: "premenstruel",
  },
  {
    handle: "vitalite-feminine",
    title: "Vitalité féminine",
    category: "infusion",
    line: "feminin",
    accent: "sauge",
    description: "Ginseng et baies de goji pour une énergie douce et durable.",
    filterKey: "feminineNeed",
    filterValue: "vitalite",
  },
  {
    handle: "confort-intime",
    title: "Confort intime",
    category: "infusion",
    line: "feminin",
    accent: "brun",
    description: "Maca et bourrache pour accompagner le bien-être intime.",
    filterKey: "feminineNeed",
    filterValue: "intime",
  },
  {
    handle: "equilibre-hormonal",
    title: "Équilibre hormonal",
    category: "infusion",
    line: "feminin",
    accent: "taupe",
    description: "Sauge et houblon pour traverser chaque saison hormonale avec sérénité.",
    filterKey: "feminineNeed",
    filterValue: "hormonal",
  },
  {
    handle: "cosmetiques-nayuma",
    title: "Cosmétiques NAYUMA",
    category: "cosmetique",
    accent: "or",
    description: "Une petite gamme de soins topiques NAYUMA, complémentaire de nos rituels infusés.",
  },
];

export const HAIR_NEED_LABELS: Record<string, string> = {
  chute: "Chute & Fortification",
  densite: "Densité & Volume",
  brillance: "Brillance & Texture",
  "cuir-chevelu": "Cuir Chevelu & Équilibre",
  "anti-stress": "Anti-Stress & Beauté",
  eclat: "Éclat & Protection",
};

export const FEMININE_NEED_LABELS: Record<string, string> = {
  cycle: "Cycle féminin",
  premenstruel: "Confort prémenstruel",
  vitalite: "Vitalité féminine",
  intime: "Confort intime",
  hormonal: "Équilibre hormonal",
};
