// Raw product specs — plain JS so both the TS data layer and the
// placeholder-image generation script can share a single source of truth.
export const productSpecs = [
  // --- RITUELS CHEVEUX (ligne "cheveux", inspirés de la gamme RACINE) ---
  {
    handle: "rituel-chute-fortification",
    title: "Rituel Chute & Fortification",
    category: "infusion",
    line: "cheveux",
    hairNeeds: ["chute"],
    feminineNeeds: [],
    accent: "cuivre",
    basePrice: 19,
    actifs: "Ortie, prêle, biotine végétale",
  },
  {
    handle: "rituel-densite-volume",
    title: "Rituel Densité & Volume",
    category: "infusion",
    line: "cheveux",
    hairNeeds: ["densite"],
    feminineNeeds: [],
    accent: "or",
    basePrice: 19,
    actifs: "Bambou, ginseng, silice végétale",
  },
  {
    handle: "rituel-brillance-texture",
    title: "Rituel Brillance & Texture",
    category: "infusion",
    line: "cheveux",
    hairNeeds: ["brillance"],
    feminineNeeds: [],
    accent: "rose",
    basePrice: 19,
    actifs: "Prêle, romarin, pépins de raisin",
  },
  {
    handle: "rituel-cuir-chevelu-equilibre",
    title: "Rituel Cuir Chevelu & Équilibre",
    category: "infusion",
    line: "cheveux",
    hairNeeds: ["cuir-chevelu"],
    feminineNeeds: [],
    accent: "sauge",
    basePrice: 19,
    actifs: "Bardane, sauge, zinc",
  },
  {
    handle: "rituel-anti-stress-beaute",
    title: "Rituel Anti-Stress & Beauté",
    category: "infusion",
    line: "cheveux",
    hairNeeds: ["anti-stress"],
    feminineNeeds: [],
    accent: "taupe",
    basePrice: 20,
    actifs: "Ashwagandha, camomille, magnésium",
  },
  {
    handle: "rituel-eclat-protection",
    title: "Rituel Éclat & Protection",
    category: "infusion",
    line: "cheveux",
    hairNeeds: ["eclat"],
    feminineNeeds: [],
    accent: "creme",
    basePrice: 20,
    actifs: "Baies de goji, vitamine E, thé blanc",
  },

  // --- RITUELS FÉMININS (ligne "féminin", inspirés de la gamme LINÉA) ---
  {
    handle: "rituel-douce-lune",
    title: "Rituel Douce Lune",
    category: "infusion",
    line: "feminin",
    hairNeeds: [],
    feminineNeeds: ["cycle"],
    accent: "rose",
    basePrice: 18,
    actifs: "Framboisier, camomille, achillée",
  },
  {
    handle: "rituel-harmonie",
    title: "Rituel Harmonie",
    category: "infusion",
    line: "feminin",
    hairNeeds: [],
    feminineNeeds: ["premenstruel"],
    accent: "terracotta",
    basePrice: 18,
    actifs: "Gattilier, mélisse, sauge",
  },
  {
    handle: "rituel-rayonnement",
    title: "Rituel Rayonnement",
    category: "infusion",
    line: "feminin",
    hairNeeds: [],
    feminineNeeds: ["vitalite"],
    accent: "sauge",
    basePrice: 18,
    actifs: "Ginseng, baies de goji, hibiscus",
  },
  {
    handle: "rituel-desir",
    title: "Rituel Désir",
    category: "infusion",
    line: "feminin",
    hairNeeds: [],
    feminineNeeds: ["intime"],
    accent: "brun",
    basePrice: 19,
    actifs: "Maca, cannelle, gingembre",
  },
  {
    handle: "rituel-intima",
    title: "Rituel Intima",
    category: "infusion",
    line: "feminin",
    hairNeeds: [],
    feminineNeeds: ["intime"],
    accent: "creme",
    basePrice: 19,
    actifs: "Bourrache, camomille, calendula",
  },
  {
    handle: "rituel-equilibre-mature",
    title: "Rituel Équilibre Mature",
    category: "infusion",
    line: "feminin",
    hairNeeds: [],
    feminineNeeds: ["hormonal"],
    accent: "taupe",
    basePrice: 19,
    actifs: "Sauge, houblon, soja fermenté",
  },

  // --- COSMÉTIQUES NAYUMA (gamme topique, à confirmer) ---
  {
    handle: "serum-capillaire-fortifiant",
    title: "Sérum Capillaire Fortifiant",
    category: "cosmetique",
    hairNeeds: ["chute", "densite"],
    feminineNeeds: [],
    accent: "cuivre",
    basePrice: 29,
    actifs: "Caféine, biotine, huile de ricin",
    flatFormat: "50 ml",
  },
  {
    handle: "huile-seche-brillance",
    title: "Huile Sèche Brillance",
    category: "cosmetique",
    hairNeeds: ["brillance", "eclat"],
    feminineNeeds: [],
    accent: "or",
    basePrice: 26,
    actifs: "Argan, jojoba, vitamine E",
    flatFormat: "75 ml",
  },
  {
    handle: "shampoing-doux-quotidien",
    title: "Shampoing Doux Quotidien",
    category: "cosmetique",
    hairNeeds: ["cuir-chevelu", "anti-stress"],
    feminineNeeds: [],
    accent: "sauge",
    basePrice: 22,
    actifs: "Avoine, aloe vera, prêle",
    flatFormat: "250 ml",
  },
];
